
version: "3.4"
services:
  cassandra:
     image: sfproductlabs/elassandra:latest
     expose:
       - "9042"
     ports:
       - "9042:9042"
       - "9160:9160"
     networks: 
       - default         
     #network_mode: host  
     #hostname: cassandra
     #container_name: cassandra
     volumes: 
       - ./.setup:/tmp/.csetup
     command: >
              bash -c "((sleep 75s && cqlsh --ssl < /tmp/.csetup/schema.3.cql && cqlsh --ssl < /tmp/.csetup/schema.4.cql &) && (/docker-entrypoint.sh cassandra -f))"
  nats:
    image: sfproductlabs/nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - default
